__uname__ = 'sqjobs'
__long_name__ = 'Simple Queue Jobs'
__version__ = '0.6.5'
__author__ = 'Jose Ignacio Galarza'
__email__ = 'igalarzab@gmail.com'
__url__ = 'http://github.com/igalarzab/sqjobs'
__license__ = 'BSD'
