version: 2
jobs:
  build-python27:
    working_directory: ~/sqjobs
    docker:
      - image: python:2.7
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: pip install -r requirements/dev.txt
      - run:
          name: Run the tests
          command: ./scripts/run_tests.sh
  build-python35:
    working_directory: ~/sqjobs
    docker:
      - image: python:3.5
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: pip install -r requirements/dev.txt
      - run:
          name: Run the tests
          command: ./scripts/run_tests.sh
  build-python36:
    working_directory: ~/sqjobs
    docker:
      - image: python:3.6
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: pip install -r requirements/dev.txt
      - run:
          name: Run the tests
          command: ./scripts/run_tests.sh

workflows:
  version: 2
  build:
    jobs:
      - build-python27
      - build-python35
      - build-python36

